apiVersion: v1
kind: Service

metadata:
  name: api-start-svc
  namespace: openmsa
spec:
  selector:
    app: api-start
  
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: http