######### 
# Service
#########


apiVersion: v1
kind: Service
metadata:
  name: simple-api-preview
  namespace: api
  labels:
    app: simple-api
spec:
  selector:
    app: simple-api
  
  ports:
  - protocol: TCP
    name: http
    port: 9090
    targetPort: http
#    nodePort: 30001
#  type: LoadBalancer