apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: backstage
  
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: jei0486/backstage-custom
  newTag: latest
